version: 1
formatters:
    simple:
        format: '%(asctime)s %(filename)s: %(message)s'
    extended:
        format: '%(asctime)s || %(levelname)s || %(filename)s -> %(funcName)s() -> [line:%(lineno)d] || %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: 'ext://sys.stdout'
    file_handler:
        class: logging.FileHandler
        level: INFO
        filename: './Logs/Test.log'
        formatter: extended
        mode: 'a'

loggers:
  dev:
    handlers: [console, file_handler]
  test:
    handlers: [file_handler]

root:
    level: DEBUG
    handlers: [console]
